account/urls.py
import django
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LoginView, LogoutView
from . import views

urlpatterns = [
    path('', views.Index.as_view(), name='index'),
    path('register/', views.register, name='register'),
    path('login/', LoginView.as_view(template_name='account/login.html'), name='login'),
    path('logout/', LogoutView.as_view(template_name='account/logout.html'), name='logout'),
]

happiness/urls.py
from django.urls import path

from . import views

app_name = 'happiness'
urlpatterns = [
    # path('', views.index, name='index'),
    path('create/', views.CreateHappiness.as_view(), name = "happiness_form"),
    path('list/', views.ListHappinessView.as_view(), name = "happiness_list"),
    path('<int:pk>/', views.ReadHappiness.as_view(), name = 'happiness_detail'),
]

mesappiness/urls.py
from django.contrib import admin
from django.urls import path, include
from account.views import Index

urlpatterns = [
    path('', Index.as_view()),
    path('happiness/', include('happiness.urls')),
    path('account/', include('account.urls')),
    path('admin/', admin.site.urls),
]

account/models.py
from django.db import models

# Create your models here.

happiness/models.py
from django.conf import settings
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator
import datetime

class Happiness(models.Model):
    date = models.DateField(default=datetime.date.today, blank=False)
    diary = models.TextField(blank = False)
    rating = models.PositiveIntegerField(
        validators=[MinValueValidator(0), MaxValueValidator(10)]
    )
    error = models.IntegerField(
                validators=[MinValueValidator(-5), MaxValueValidator(5)]
    )
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        blank=True,
        null=True,
        related_name="happiness",
        on_delete=models.CASCADE,
    )

    def __str__(self):
        sign = "+"
        if self.error < 0:
            sign = ""
        return self.date.strftime("%m/%d/%Y") + " - " + str(self.rating) + " Error: " + sign + str(self.error)

account/forms.py
from pyexpat import model
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Confirm password', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']
        help_texts = {k:"" for k in fields}

happiness/forms.py
from django import forms

from happiness.models import Happiness


class HappinessForm(forms.ModelForm):

    class Meta:
        model = Happiness
        fields = [
            'date',
            'diary',
            'rating',
            'error',   
        ]

        labels = {
            'date': 'Date',
            'diary': 'Diary',
            'rating': 'Rating',
            'error': 'Error',
        }

    def __init__(self, *args, **kwargs):
        self.user = kwargs['initial']['user']
        super(HappinessForm, self).__init__(*args, **kwargs)
    
    def save(self, commit=True):
        obj = super(HappinessForm, self).save(False)
        obj.user = self.user
        commit and obj.save()
        return obj

        

account/views.py
from audioop import reverse
from django.shortcuts import redirect, render
from django.contrib import messages
from django.views.generic import TemplateView

from mesappiness.settings import LANGUAGE_CODE
from .forms import UserRegisterForm
from django.utils.translation import gettext_lazy as _

class Index(TemplateView):
    template_name = 'account/index.html'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['username'] = _(self.request.user.username)
        context['language_code'] = LANGUAGE_CODE
        return context

def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data['username']
            messages.success(request, f'User {username} created')
            return redirect('index')
    else:
        form = UserRegisterForm()
    context = {'form': form}
    return render(request, 'account/register.html', context)

happiness/views.py
from django.views import generic

from happiness.forms import HappinessForm
from happiness.models import Happiness

class ListHappinessView(generic.ListView):
    template_name = 'happiness/list_happiness.html'
    context_object_name = 'happiness_list'
    paginate_by = 5
    model = Happiness

    def get_queryset(self):
        return Happiness.objects.filter(user=self.request.user)


class CreateHappiness(generic.CreateView):
    template_name = 'happiness/happiness_form.html'
    form_class = HappinessForm
    success_url = '/happiness/list'

    def get_initial(self):
        self.initial.update({ 'user': self.request.user })
        return self.initial


class ReadHappiness(generic.DetailView):
    model = Happiness
    template_name = 'happiness/happiness_detail.html'

happiness/templates/happiness/happiness_detail.html
{% extends 'account/layout.html' %}

{% block content %}

<div>
    <h1 style="text-align: center;">
        Register Details
    </h1>

   <h2>
       {{ happiness.date }}
   </h2>

   <h2>Rating: {{ happiness.rating }}, Error: {{ happiness.error }}</h2>

   <p>{{ happiness.diary }}</p>

</div>

{% endblock %}

happiness/templates/happiness/happiness_form.html
{% extends 'account/layout.html' %}

{% block content %}

<form class="form" method="post" enctype="multipart/form-data">
    {{ form.as_p }}
    {% csrf_token %}
    <button type = "submit">Submit</button>
</form>

{% endblock %}

happiness/templates/happiness/index.html
{% extends 'account/layout.html' %}

{% load i18n %}

{% block content %}

    <h1>{% trans 'Home page' %}</h1>

    <p>
        {% blocktrans trimmed %}
            This project is based on research made by Alejandro Cencerrado,
            a physicist who works at the Happiness Research Institute of Copenhague.
        {% endblocktrans %}
    </p>

{% endblock %}  

happiness/templates/happiness/list_happiness.html
{% extends 'account/layout.html' %}

{% block content %}

<h1 style="text-align:center;">
    Your entries
</h1>
<div>
    {% if happiness_list %}
    <table>
        {% for happiness in happiness_list %}
            <tr>
                <td>
                    <p>{{ happiness.date }}</p>
                </td>
                <td>
                    <p>{{ happiness.rating }}</p>
                </td>
                <td>
                    <a href="{% url 'happiness:happiness_detail' happiness.id %}">
                        <button>View details</button>
                    </a>
                </td>
            </tr>
        {% endfor %}
    </table>

    <div class="pagination" style="text-align: center;">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="?page=1">&laquo;First</a>
                <a href="?page={{page_obj.previous_page_number}}">Previous</a>
            {% endif %}

            <span class="current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </span>
            
            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">next</a>
                <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </div>
    {% endif %}
</div>

{% endblock %}